"""
MCP Memory Proxy - Configuration
Date: 2026-02-15
Purpose: Centralized configuration for MCP Memory Proxy service
"""
import os
from typing import List

# Google Sheet Configuration
GOOGLE_SHEET_ID = os.environ.get("GOOGLE_SHEET_ID", "1kq83HL78CeJsG6s2TGkqr6Sre7BAK7mhhZYwrPIUjQQ")

# Service Account Configuration
# The service account JSON key should be mounted or provided via environment
SERVICE_ACCOUNT_KEY_PATH = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "/app/sa-key.json")

# Operational Configuration
READ_ONLY_MODE = os.environ.get("READ_ONLY_MODE", "false").lower() == "true"
ENABLE_NOTIFICATIONS = os.environ.get("ENABLE_NOTIFICATIONS", "false").lower() == "true"
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "production")  # production or dev

# Drive Configuration
ARCHIVES_FOLDER_ID = os.environ.get("ARCHIVES_FOLDER_ID", "")  # Will be read from SETTINGS sheet

# Expected Sheet Tabs (18 tabs)
EXPECTED_TABS = [
    "MEMORY_LOG",
    "SNAPSHOT_ACTIVE",
    "REGLES_DE_GOUVERNANCE",
    "ARCHITECTURE_GLOBALE",
    "CARTOGRAPHIE_APPELS",
    "DEPENDANCES_SCRIPTS",
    "TRIGGERS_ET_TIMERS",
    "CONFLITS_DETECTES",
    "RISKS",
    "SETTINGS",
    "LOGS_SYSTEM",
    "INDEX_FACTURES",
    "PROPOSITIONS_PENDING",
    "BOX_CONFIG",
    "SUPPLIERS_MEMORY",
    "VALIDATION_RULES",
    "AUDIT_TRAIL",
    "PERFORMANCE_METRICS"
]

# API Configuration
# Version is read from VERSION env var (set at deployment) or falls back to hardcoded value
API_VERSION = os.environ.get("VERSION", "3.0.5")
API_TITLE = "MCP Memory Proxy"
API_DESCRIPTION = "REST API for GPT access to IAPF Memory Hub"

# Build/Deployment Information (fallback values, prefer env vars)
BUILD_VERSION = os.environ.get("BUILD_VERSION", "3.0.1")
GIT_COMMIT_SHA = os.environ.get("GIT_COMMIT", "6731d42")

# Security
ALLOWED_ORIGINS = os.environ.get("ALLOWED_ORIGINS", "*").split(",")

# API Key Authentication
API_KEY = os.environ.get("API_KEY", "")  # Set via environment variable
API_KEY_HEADER = "X-API-Key"

# Proposal Configuration
PROPOSAL_ID_PREFIX = "PROP"
PROPOSAL_STATUS_PENDING = "PENDING"
PROPOSAL_STATUS_APPROVED = "APPROVED"
PROPOSAL_STATUS_REJECTED = "REJECTED"

# Memory Log Configuration
MEMORY_LOG_SHEET = "MEMORY_LOG"
PROPOSITIONS_PENDING_SHEET = "PROPOSITIONS_PENDING"
SNAPSHOT_SHEET = "SNAPSHOT_ACTIVE"
SETTINGS_SHEET = "SETTINGS"
CARTOGRAPHIE_SHEET = "CARTOGRAPHIE_APPELS"
DEPENDANCES_SHEET = "DEPENDANCES_SCRIPTS"
ARCHITECTURE_SHEET = "ARCHITECTURE_GLOBALE"

# Logging
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Timezone Configuration
# All timestamps generated by the proxy are in UTC (ISO 8601)
# Metadata for bureau Mehdi timezone (for reference only, not used for generation)
BUREAU_TIMEZONE = "Europe/Paris"  # UTC+1 (winter) / UTC+2 (summer)
BUREAU_TIMEZONE_OFFSET = "+01:00"  # Standard offset (winter)

# ACTION Configuration (PREPARED BUT DISABLED BY DEFAULT)
# All write/deploy operations require double validation and are disabled by default
ENABLE_ACTIONS = os.environ.get("ENABLE_ACTIONS", "false").lower() == "true"
DRY_RUN_MODE = os.environ.get("DRY_RUN_MODE", "true").lower() == "true"

# GCP Project Configuration
# Supports both MCP_* and legacy naming (fallback to legacy if MCP_* not set)
GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "box-magique-gp-prod")
GCP_REGION = os.environ.get("GCP_REGION", "us-central1")
CLOUD_RUN_SERVICE = os.environ.get("CLOUD_RUN_SERVICE", "mcp-memory-proxy")

# ============================================================================
# PHASE 2 CONFIGURATION - Extension contrôlée des accès MCP
# Standardisation variables: MCP_* (preferred) with fallback to legacy names
# ============================================================================

# MCP Environment
# Supports: MCP_ENVIRONMENT (preferred) or ENVIRONMENT (legacy)
MCP_ENVIRONMENT = os.environ.get("MCP_ENVIRONMENT") or os.environ.get("ENVIRONMENT", "STAGING")

# MCP GCP Configuration
# Supports: MCP_GCP_PROJECT_ID (preferred) or GCP_PROJECT_ID (legacy)
MCP_GCP_PROJECT_ID = os.environ.get("MCP_GCP_PROJECT_ID") or GCP_PROJECT_ID

# Supports: MCP_GCP_REGION (preferred) or GCP_REGION (legacy)
MCP_GCP_REGION = os.environ.get("MCP_GCP_REGION") or GCP_REGION

# Supports: MCP_CLOUD_RUN_SERVICE (preferred) or CLOUD_RUN_SERVICE (legacy)
MCP_CLOUD_RUN_SERVICE = os.environ.get("MCP_CLOUD_RUN_SERVICE") or CLOUD_RUN_SERVICE

# Web Access Configuration
MCP_WEB_ALLOWED_DOMAINS = os.environ.get(
    "MCP_WEB_ALLOWED_DOMAINS",
    "developers.google.com,cloud.google.com,googleapis.dev"
).split(",")
MCP_WEB_QUOTA_DAILY = int(os.environ.get("MCP_WEB_QUOTA_DAILY", "100"))

# Terminal Configuration
MCP_TERMINAL_QUOTA_DAILY_READ = int(os.environ.get("MCP_TERMINAL_QUOTA_DAILY_READ", "50"))
MCP_TERMINAL_QUOTA_DAILY_WRITE = int(os.environ.get("MCP_TERMINAL_QUOTA_DAILY_WRITE", "10"))

# Settings wrapper
class Settings:
    # Existing config
    GOOGLE_SHEET_ID = GOOGLE_SHEET_ID
    SERVICE_ACCOUNT_KEY_PATH = SERVICE_ACCOUNT_KEY_PATH
    READ_ONLY_MODE = READ_ONLY_MODE
    ENABLE_ACTIONS = ENABLE_ACTIONS
    DRY_RUN_MODE = DRY_RUN_MODE
    API_VERSION = API_VERSION
    API_KEY = API_KEY
    GCP_PROJECT_ID = GCP_PROJECT_ID
    GCP_REGION = GCP_REGION
    
    # Phase 2 config
    MCP_ENVIRONMENT = MCP_ENVIRONMENT
    MCP_GCP_PROJECT_ID = MCP_GCP_PROJECT_ID
    MCP_GCP_REGION = MCP_GCP_REGION
    MCP_CLOUD_RUN_SERVICE = MCP_CLOUD_RUN_SERVICE
    MCP_WEB_ALLOWED_DOMAINS = MCP_WEB_ALLOWED_DOMAINS
    MCP_WEB_QUOTA_DAILY = MCP_WEB_QUOTA_DAILY
    MCP_TERMINAL_QUOTA_DAILY_READ = MCP_TERMINAL_QUOTA_DAILY_READ
    MCP_TERMINAL_QUOTA_DAILY_WRITE = MCP_TERMINAL_QUOTA_DAILY_WRITE


def get_settings():
    """Get settings instance"""
    return Settings()
