"""
MCP Memory Proxy - Configuration
Date: 2026-02-15
Purpose: Centralized configuration for MCP Memory Proxy service
"""
import os
from typing import List

# Google Sheet Configuration
GOOGLE_SHEET_ID = os.environ.get("GOOGLE_SHEET_ID", "1kq83HL78CeJsG6s2TGkqr6Sre7BAK7mhhZYwrPIUjQQ")

# Service Account Configuration
# The service account JSON key should be mounted or provided via environment
SERVICE_ACCOUNT_KEY_PATH = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "/app/sa-key.json")

# Operational Configuration
READ_ONLY_MODE = os.environ.get("READ_ONLY_MODE", "false").lower() == "true"
ENABLE_NOTIFICATIONS = os.environ.get("ENABLE_NOTIFICATIONS", "false").lower() == "true"
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "production")  # production or dev

# Drive Configuration
ARCHIVES_FOLDER_ID = os.environ.get("ARCHIVES_FOLDER_ID", "")  # Will be read from SETTINGS sheet

# Expected Sheet Tabs (18 tabs)
EXPECTED_TABS = [
    "MEMORY_LOG",
    "SNAPSHOT_ACTIVE",
    "REGLES_DE_GOUVERNANCE",
    "ARCHITECTURE_GLOBALE",
    "CARTOGRAPHIE_APPELS",
    "DEPENDANCES_SCRIPTS",
    "TRIGGERS_ET_TIMERS",
    "CONFLITS_DETECTES",
    "RISKS",
    "SETTINGS",
    "LOGS_SYSTEM",
    "INDEX_FACTURES",
    "PROPOSITIONS_PENDING",
    "BOX_CONFIG",
    "SUPPLIERS_MEMORY",
    "VALIDATION_RULES",
    "AUDIT_TRAIL",
    "PERFORMANCE_METRICS"
]

# API Configuration
API_VERSION = "3.0.3"  # Dual-mode auth: IAM OR API-Key for /sheets/*
API_TITLE = "MCP Memory Proxy"
API_DESCRIPTION = "REST API for GPT access to IAPF Memory Hub"

# Build/Deployment Information
BUILD_VERSION = "3.0.1"
GIT_COMMIT_SHA = "6731d42"  # Updated with each deployment

# Security
ALLOWED_ORIGINS = os.environ.get("ALLOWED_ORIGINS", "*").split(",")

# API Key Authentication
API_KEY = os.environ.get("API_KEY", "")  # Set via environment variable
API_KEY_HEADER = "X-API-Key"

# Proposal Configuration
PROPOSAL_ID_PREFIX = "PROP"
PROPOSAL_STATUS_PENDING = "PENDING"
PROPOSAL_STATUS_APPROVED = "APPROVED"
PROPOSAL_STATUS_REJECTED = "REJECTED"

# Memory Log Configuration
MEMORY_LOG_SHEET = "MEMORY_LOG"
PROPOSITIONS_PENDING_SHEET = "PROPOSITIONS_PENDING"
SNAPSHOT_SHEET = "SNAPSHOT_ACTIVE"
SETTINGS_SHEET = "SETTINGS"
CARTOGRAPHIE_SHEET = "CARTOGRAPHIE_APPELS"
DEPENDANCES_SHEET = "DEPENDANCES_SCRIPTS"
ARCHITECTURE_SHEET = "ARCHITECTURE_GLOBALE"

# Logging
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Timezone Configuration
# All timestamps generated by the proxy are in UTC (ISO 8601)
# Metadata for bureau Mehdi timezone (for reference only, not used for generation)
BUREAU_TIMEZONE = "Europe/Paris"  # UTC+1 (winter) / UTC+2 (summer)
BUREAU_TIMEZONE_OFFSET = "+01:00"  # Standard offset (winter)

# ACTION Configuration (PREPARED BUT DISABLED BY DEFAULT)
# All write/deploy operations require double validation and are disabled by default
ENABLE_ACTIONS = os.environ.get("ENABLE_ACTIONS", "false").lower() == "true"
DRY_RUN_MODE = os.environ.get("DRY_RUN_MODE", "true").lower() == "true"

# GCP Project Configuration
GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "box-magique-gp-prod")
GCP_REGION = os.environ.get("GCP_REGION", "us-central1")
